### PR TITLE
Upgrade dependent prometheus plugin

### LINKED ISSUE #4: This plugin does not work with Ruby 3.0
prometheus-client 0.9.0 still uses `URI.escape` but this method had been removed since Ruby 3.0:

```irb
irb> require 'uri'
=> false
irb> URI.escape("http://localhost:24224/")
(irb):2:in `<main>': undefined method `escape' for URI:Module (NoMethodError)
	from ~/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/irb-1.3.5/exe/irb:11:in `<top (required)>'
	from ~/.rbenv/versions/3.0.1/bin/irb:23:in `load'
	from ~/.rbenv/versions/3.0.1/bin/irb:23:in `<main>'
irb> RUBY_VERSION
=> "3.0.1"
```

We should update dependent prometheus client to be Ruby 3.0 workable version.

But I'm not sure that the latest prometheus client has enough API to be working well with this plugin.

### PR DESCRIPTION
**Pull request by cosmo0920**
It should be upgraded dependent prometheus plugin due to Ruby 3.0.
Ruby 3.0 removes URI.escape which is warned deprecated method for a long
time.

Closes #4.

Signed-off-by: Hiroshi Hatake <hatake@calyptia.com>

### CODE REVIEW

**Review by ashie — APPROVED** [review]

**Comment by cosmo0920** [comment]
prometheus gateway can be working with:
```console
$ docker run -p 9091:9091 prom/pushgateway 
level=info ts=2021-04-20T05:01:50.035Z caller=main.go:85 msg="starting pushgateway" version="(version=1.4.0, branch=HEAD, revision=007ba874bead1b9ad2253d89e3adeb16a73fd012)"
level=info ts=2021-04-20T05:01:50.035Z caller=main.go:86 build_context="(go=go1.15.7, user=root@410bc05a48f6, date=20210122-23:54:24)"
level=info ts=2021-04-20T05:01:50.052Z caller=main.go:139 listen_address=:9091
level=info ts=2021-04-20T05:01:50.056Z caller=tls_config.go:191 msg="TLS is disabled." http2=false
```

This change make to be able to push registry information with Ruby 3.0:

```console
$ curl -X GET http://localhost:9091/api/v1/metrics | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   888  100   888    0     0  13454      0 --:--:-- --:--:-- --:--:-- 13454
```
```json
{
  "status": "success",
  "data": [
    {
      "fluent_in_dummy_message": {
        "time_stamp": "2021-04-20T05:02:46.125358Z",
        "type": "COUNTER",
        "help": "dummy messsage count",
        "metrics": [
          {
            "labels": {
              "host": "Hiroshi-no-MacBook-Pro.local",
              "instance": "",
              "job": "fleuntd_prometheus_pushgateway:0"
            },
            "value": "12"
          }
        ]
      },
      "labels": {
        "job": "fleuntd_prometheus_pushgateway:0"
      },
      "last_push_successful": true,
      "push_failure_time_seconds": {
        "time_stamp": "2021-04-20T05:02:05.4149954Z",
        "type": "GAUGE",
        "help": "Last Unix time when changing this group in the Pushgateway failed.",
        "metrics": [
          {
            "labels": {
              "instance": "",
              "job": "fleuntd_prometheus_pushgateway:0"
            },
            "value": "0"
          }
        ]
      },
      "push_time_seconds": {
        "time_stamp": "2021-04-20T05:02:46.125358Z",
        "type": "GAUGE",
        "help": "Last Unix time when changing this group in the Pushgateway succeeded.",
        "metrics": [
          {
            "labels": {
              "instance": "",
              "job": "fleuntd_prometheus_pushgateway:0"
            },
            "value": "1.618894966125358e+09"
          }
        ]
      }
    }
  ]
}
```

**Comment by cosmo0920** [comment]
Is there any ETA to be released a new version which is compatible with Ruby 3.0?
