### ISSUE TITLE
This plugin does not work with Ruby 3.0

### ISSUE THREAD

**Issue by cosmo0920** [fluent/fluent-plugin-prometheus_pushgateway#4]
prometheus-client 0.9.0 still uses `URI.escape` but this method had been removed since Ruby 3.0:

```irb
irb> require 'uri'
=> false
irb> URI.escape("http://localhost:24224/")
(irb):2:in `<main>': undefined method `escape' for URI:Module (NoMethodError)
	from ~/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/irb-1.3.5/exe/irb:11:in `<top (required)>'
	from ~/.rbenv/versions/3.0.1/bin/irb:23:in `load'
	from ~/.rbenv/versions/3.0.1/bin/irb:23:in `<main>'
irb> RUBY_VERSION
=> "3.0.1"
```

We should update dependent prometheus client to be Ruby 3.0 workable version.

But I'm not sure that the latest prometheus client has enough API to be working well with this plugin.
